apiVersion: v1
kind: Namespace
metadata:
  name: ibm-license-service-reporter
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: ibm-license-service-reporter
spec:
  targetNamespaces:
  - ibm-license-service-reporter
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-license-service-reporter-operator
  namespace: ibm-license-service-reporter
spec:
  channel: v4.2
  installPlanApproval: Automatic
  name: ibm-license-service-reporter-operator
  source: ibm-license-service-reporter-bundle-catalog
  sourceNamespace: openshift-marketplace