apiVersion: integration.ibm.com/v1beta1
kind: PlatformNavigator
metadata:
  name: integration-quickstart
  namespace: cp4i-demo
  labels:
    backup.integration.ibm.com/component: platformnavigator        
spec:
  license:
    accept: true
    license: L-QYVA-B365MB
  replicas: 1
  version: 16.1.1
