kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
    imageURL: bastion.gym.lan:8443/mirror/oc-mirror-metadata
    skipTLS: true
mirror:
  platform:
    channels:
    - name: stable-4.16
      type: ocp
      minVersion: 4.16.37
      maxVersion: 4.16.37      
    graph: true  
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.16
    packages:
    - name: odf-operator
      channels:
      - name: stable-4.16
    - name: openshift-cert-manager-operator
      channels:
      - name: stable-v1          
    - name: openshift-gitops-operator
      channels:
      - name: latest
    - name: rhbk-operator
      channels:
      - name: stable-v24          
  additionalImages:
  - name: registry.redhat.io/ubi8/ubi:latest
  helm: {}
