kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    channels:
    - name: stable-4.18
      type: ocp
      minVersion: 4.18.8
      maxVersion: 4.18.8      
    graph: true  
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.18
    packages:
    - name: odf-operator
      channels:
      - name: stable-4.18
    - name: openshift-cert-manager-operator
      channels:
      - name: stable-v1          
    - name: openshift-gitops-operator
      channels:
      - name: latest
    - name: rhbk-operator
      channels:
      - name: stable-v26.0          
  additionalImages:
  - name: registry.redhat.io/ubi8/ubi:latest
  helm: {}
