kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
    imageURL: bastion.gym.lan:8443/mirror/oc-mirror-metadata
    skipTLS: false
mirror:
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.16
    packages:
    - name: rhbk-operator
      channels:
      - name: stable-v24          
    - name: cert-manager
      channels:
      - name: stable-v1.15               
  additionalImages:
  - name: registry.redhat.io/ubi8/ubi:latest
  helm: {}
