apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: exampleqm
spec:
  license:
    accept: true
    license: L-QYVA-B365MB
    use: NonProduction
  queueManager:
    name: EXAMPLEQM
    availability:
      type: NativeHA
      tls:
        secretName: nhacrr-london-int
    mqsc:
    - configMap:
        name: nhacrr-london-configmap
        items:
        - example-tls.mqsc
    ini:
    - configMap:
        name: nhacrr-london-configmap
        items:
        - example-tls.ini
    storage:
      queueManager:
        type: persistent-claim
  version: 9.4.2.0-r2
  pki:
    keys:
      - name: default
        secret:
          secretName: nhacrr-london-app
          items:
            - tls.key
            - tls.crt
            - ca.crt
  web:
    console:
      authentication:
        provider: integration-keycloak
      authorization:
        provider: integration-keycloak
    enabled: true            