apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: exampleqm
spec:
  license:
    accept: true
    license: L-QYVA-B365MB
    use: NonProduction
  queueManager:
    name: EXAMPLEQM
    availability:
      type: NativeHA
      tls:
        secretName: nhacrr-rome-int
    mqsc:
    - configMap:
        name: nhacrr-rome-configmap
        items:
        - example-tls.mqsc
    ini:
    - configMap:
        name: nhacrr-rome-configmap
        items:
        - example-tls.ini
    availability:       
      nativeHAGroups:
        local:
          name: Rome_group
          role: Recovery
          tls:
            key:
              items:
                - tls.key
                - tls.crt
              secretName: nhacrr-rome-ext
        remotes: 
          - addresses:
              - 'exampleqm-ibm-mq-nhacrr-cp4i-demo.apps.cp4i.gym.lan:443'
            name: London_group
            trust: 
              - secret:   
                  items:
                    - tls.crt       
                  secretName: nhacrr-london-ext
    storage:
      queueManager:
        type: persistent-claim
  version: 9.4.2.0-r2
  pki:
    keys:
      - name: default
        secret:
          secretName: nhacrr-rome-app
          items:
            - tls.key
            - tls.crt
            - ca.crt
  web:
    console:
      authentication:
        provider: integration-keycloak
      authorization:
        provider: integration-keycloak
    enabled: true            