kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: nhacrr-london-app
  namespace: cp4i-demo
spec:
  commonName: selfsigned-ca.dns.name
  subject: 
    organizations:
    - cp4i
  issuerRef:
     name: osm-ca
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  secretName: nhacrr-london-app
---
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: nhacrr-london-int
  namespace: cp4i-demo
spec:
  commonName: selfsigned-ca.dns.name
  subject: 
    organizations:
    - cp4i  
  issuerRef:
     name: osm-ca
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  secretName: nhacrr-london-int
---
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: nhacrr-london-ext
  namespace: cp4i-demo
spec:
  commonName: selfsigned-ca.dns.name
  subject: 
    organizations:
    - cp4i
  issuerRef:
     name: osm-ca
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  secretName: nhacrr-london-ext
---
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: nhacrr-rome-app
  namespace: cp4i-demo
spec:
  commonName: selfsigned-ca.dns.name
  issuerRef:
     name: osm-ca
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  secretName: nhacrr-rome-app
---
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: nhacrr-rome-int
  namespace: cp4i-demo
spec:
  commonName: selfsigned-ca.dns.name
  issuerRef:
     name: osm-ca
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  secretName: nhacrr-rome-int
---
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: nhacrr-rome-ext
  namespace: cp4i-demo
spec:
  commonName: selfsigned-ca.dns.name
  issuerRef:
     name: osm-ca
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  secretName: nhacrr-rome-ext
---